In [1]:
import pandas as pd
df= pd.read_csv("cleaned.csv")
df=df[['selftext','score']]
df=df.dropna()
#df= df[df['type']=="Adult"]
df

                                               selftext  score
0     realize pretty vague honestly mind long simply...      1
1     know long shot looking song month luck hoping ...      3
2     post dedicated finding unknown unidentifiable ...      4
3                                kind remix like best d      1
4     like minimal micro house playlist you perfect ...      3
...                                                 ...    ...
3879                              would appreciate much     13
3880  looking house track long drum break conga djem...      1
3881  trying get year contacted label said would sho...      1
3882  mine in particular order hard omar s heard che...     11
3883  hey guy first post reddit please bare making m...      2

[3305 rows x 2 columns]

In [2]:
import numpy as np
emo = pd.read_csv('./EMOTION.csv')
emo.columns=['word','emotion','score']
emo=emo[emo['score']>=0.5]
#len(emo)1606
#len(emo[emo['emotion']=='anger'])278
#len(emo[emo['emotion']=='fear'])341
#len(emo[emo['emotion']=='sadness'])249
#len(emo[emo['emotion']=='surprise'])104
#len(emo[emo['emotion']=='anticipation'])53
#len(emo[emo['emotion']=='joy'])283
#len(emo[emo['emotion']=='trust'])118
#len(emo[emo['emotion']=='disgust'])180

emo=emo.reset_index()
emo.columns
del emo['index']
emo['emotion'].unique()

array(['anger', 'anticipation', 'disgust', 'fear', 'joy', 'sadness',
       'surprise', 'trust'], dtype=object)

In [3]:
len(emo[emo['emotion']=='anger'])

755

In [4]:
df[['anger', 'anticipation', 'disgust', 'fear', 'joy', 'sadness',
       'surprise', 'trust']]=0

df

,selftext,score,anger,anticipation,disgust,fear,joy,sadness,surprise,trust
0,realize pretty vague honestly mind long simply...,1,0,0,0,0,0,0,0,0
1,know long shot looking song month luck hoping ...,3,0,0,0,0,0,0,0,0
2,post dedicated finding unknown unidentifiable ...,4,0,0,0,0,0,0,0,0
3,kind remix like best d,1,0,0,0,0,0,0,0,0
4,like minimal micro house playlist you perfect ...,3,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
3879,would appreciate much,13,0,0,0,0,0,0,0,0
3880,looking house track long drum break conga djem...,1,0,0,0,0,0,0,0,0
3881,trying get year contacted label said would sho...,1,0,0,0,0,0,0,0,0
3882,mine in particular order hard omar s heard che...,11,0,0,0,0,0,0,0,0
3883,hey guy first post reddit please bare making m...,2,0,0,0,0,0,0,0,0

In [5]:
for i in range(len(emo)):
    index=df[df['selftext'].str.contains(emo.iloc[i]['word'])].index
    for j in range(len(index)):
        ind=index[j]
        score = emo.iloc[i]['score']
        column_index=emo.iloc[i]['emotion']
        original=df.at[ind,column_index]
        df.at[ind,column_index]=original+ score *100

In [6]:
df

,selftext,score,anger,anticipation,disgust,fear,joy,sadness,surprise,trust
0,realize pretty vague honestly mind long simply...,1,0,0,0,0,68,0,0,148
1,know long shot looking song month luck hoping ...,3,119,187,119,73,292,108,121,75
2,post dedicated finding unknown unidentifiable ...,4,54,0,0,110,0,60,66,128
3,kind remix like best d,1,0,0,0,0,62,0,0,64
4,like minimal micro house playlist you perfect ...,3,54,0,62,56,264,51,0,109
...,...,...,...,...,...,...,...,...,...,...
3879,would appreciate much,13,0,0,0,0,0,0,0,0
3880,looking house track long drum break conga djem...,1,0,75,56,0,82,0,0,150
3881,trying get year contacted label said would sho...,1,54,0,127,56,54,111,0,61
3882,mine in particular order hard omar s heard che...,11,235,520,267,333,1148,218,163,385
3883,hey guy first post reddit please bare making m...,2,0,64,65,0,129,0,0,255

In [7]:
# get the column name of max values in every row
df['label']=df[['anger', 'anticipation', 'disgust', 'fear', 'joy', 'sadness',
       'surprise', 'trust']].idxmax(axis="columns")
df

,selftext,score,anger,anticipation,disgust,fear,joy,sadness,surprise,trust,label
0,realize pretty vague honestly mind long simply...,1,0,0,0,0,68,0,0,148,trust
1,know long shot looking song month luck hoping ...,3,119,187,119,73,292,108,121,75,joy
2,post dedicated finding unknown unidentifiable ...,4,54,0,0,110,0,60,66,128,trust
3,kind remix like best d,1,0,0,0,0,62,0,0,64,trust
4,like minimal micro house playlist you perfect ...,3,54,0,62,56,264,51,0,109,joy
...,...,...,...,...,...,...,...,...,...,...,...
3879,would appreciate much,13,0,0,0,0,0,0,0,0,anger
3880,looking house track long drum break conga djem...,1,0,75,56,0,82,0,0,150,trust
3881,trying get year contacted label said would sho...,1,54,0,127,56,54,111,0,61,disgust
3882,mine in particular order hard omar s heard che...,11,235,520,267,333,1148,218,163,385,joy
3883,hey guy first post reddit please bare making m...,2,0,64,65,0,129,0,0,255,trust

In [8]:
#remove stopwords
import nltk
from nltk.corpus import stopwords
#nltk.download("stopwords") #uncomment it when run it for the first time
stop_words = set(stopwords.words("english"))

def remove_stopwords(text):
    text = " ".join([word for word in text.split() if word not in stop_words])
    return text

stop_words.update({'would','k','im','could','also',
                   'amp','much','one','like',
                   'since','etc','got','always',
                   'know','wa','thing','really',
                   'feel','find','even','go','would','well'
                  })
df['selftext']=df['selftext'].apply(lambda x: remove_stopwords(x))

In [9]:
anticipation_df=df[df['label']=='anticipation']
anticipation_df

,selftext,score,anger,anticipation,disgust,fear,joy,sadness,surprise,trust,label
24,swimming place,1,0,50,0,0,0,0,0,0,anticipation
58,tell housey scene end moment curious see answer,4,0,120,0,59,0,0,0,0,anticipation
105,least year old kind moody vibe female vocal th...,3,0,188,54,60,62,0,0,175,anticipation
123,anybody planet song,1,0,56,0,0,0,0,0,0,anticipation
129,remember looking waiting release version stumb...,1,56,118,56,0,71,50,0,53,anticipation
...,...,...,...,...,...,...,...,...,...,...,...
3840,check new tab occasionally quality house submi...,10,175,286,82,72,189,65,280,186,anticipation
3848,hey guy started producing deep house love hear...,11,0,152,0,0,140,0,0,143,anticipation
3850,something discus lil louis working documentary...,5,0,56,0,0,0,0,0,53,anticipation
3861,hope post break rule sub,3,0,77,0,0,58,0,0,68,anticipation
3865,hello everyone hope life treating current pand...,1,160,380,238,209,308,145,0,249,anticipation

In [10]:
#n-grams for anticipation
from nltk.util import ngrams
import itertools
import collections
def count_2gram(text):
    all_words = list(itertools.chain(*text.str.split()))
    es2grams = ngrams(all_words, 2)
    counts = collections.Counter(es2grams)
    count_df = pd.DataFrame(counts.most_common(100),
                            columns=['words', 'count'])
    dictionary2 = [' '.join(tup) for tup in count_df.words]
    count_df.words=dictionary2

    return count_df

count_df2=count_2gram(anticipation_df['selftext'])
count_df2.head(20)

                words  count
0      thanks advance     29
1        original mix     19
2          deep house     16
3         house track     14
4         disco house     11
5         track start     10
6          song start     10
7             hey guy      9
8             r house      9
9       thank advance      8
10         tech house      8
11           hope guy      7
12         house song      7
13       start around      7
14         mix posted      7
15  progressive house      7
16         first time      6
17    youtube channel      6
18            new mix      6
19        boiler room      5

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer
#analyzer=â€˜char_wbâ€™
def tfidfvectorizer(df):
    vec=TfidfVectorizer(min_df=0.01,stop_words='english',ngram_range=(2,3))
    counts=vec.fit_transform(df['selftext'])
    counts=counts.toarray()
    count_df1=pd.DataFrame(counts,columns=vec.get_feature_names())
    return count_df1

count_df1=tfidfvectorizer(anticipation_df)
count_df1

,antal hunee,city drum,city drum ensemble,david vunk,deep house,disco house,dj mix,drum ensemble,favourite track,guy started,...,new york,old school,original mix,progressive house,song start,tech house,thank advance,thanks advance,track start,youtube channel
0,0.0,0.0,0.0,0.0,0.000000,0.00000,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
1,0.0,0.0,0.0,0.0,0.000000,0.00000,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
2,0.0,0.0,0.0,0.0,0.000000,0.00000,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
3,0.0,0.0,0.0,0.0,0.000000,0.00000,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
4,0.0,0.0,0.0,0.0,0.000000,0.00000,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
317,0.0,0.0,0.0,0.0,0.000000,0.00000,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
318,0.0,0.0,0.0,0.0,0.511512,0.00000,0.0,0.0,0.0,0.649598,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
319,0.0,0.0,0.0,0.0,0.000000,0.00000,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
320,0.0,0.0,0.0,0.0,0.000000,0.00000,0.0,0.0,0.0,0.000000,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0
321,0.0,0.0,0.0,0.0,0.000000,0.37361,0.0,0.0,0.0,0.000000,...,0.0,0.881736,0.0,0.0,0.0,0.0,0.0,0.288024,0.0,0.0

In [12]:
from sklearn.decomposition import NMF

#n-components=number of topics
def nmf_topic(n_components,df):
    n=n_components
    model1=NMF(n_components=n,init="random",random_state=0)
    return model1.fit(df)

model1=nmf_topic(4,count_df1)
model1

NMF(init='random', n_components=4, random_state=0)

In [13]:
import numpy as np
def top_words(X, model, component, num_words):
    """
    Extract the top words from the specified component 
    for a topic model trained on data. 
    X: a term-document matrix, assumed to be a pd.DataFrame
    model: a sklearn model with a components_ attribute, e.g. NMF
    component: the desired component, specified as an integer. 
        Must be less than than the total number of components in model
    num_words: the number of words to return.
    """
    orders = np.argsort(model.components_, axis = 1)
    important_words = np.array(X.columns)[orders]
    return important_words[component][-num_words:]

In [14]:
#topic modeling for anticipation
topic1=pd.DataFrame({'Topic 0':top_words(count_df1, model1, 0, 10),
                   'Topic 1':top_words(count_df1, model1, 1, 10),
                   'Topic 2':top_words(count_df1, model1, 2, 10),
                     'Topic 3':top_words(count_df1, model1, 3, 10),
                   })
topic1

       Topic 0            Topic 1            Topic 2          Topic 3
0   old school         house deep         old school          new mix
1  antal hunee    favourite track           new york  favourite track
2   david vunk    youtube channel  progressive house      guy started
3     new york         tech house    youtube channel          hey guy
4   tech house        disco house           live set           hi guy
5     id track  progressive house           id track       house song
6     hope guy            hey guy         house song     original mix
7   house song           hope guy       house artist       house deep
8   song start      thank advance        disco house        house mix
9  track start        house track     thanks advance       deep house

In [15]:
#topic modeling for fear
fear_df=df[df['label']=='fear']

count_df1=tfidfvectorizer(fear_df)
model1=nmf_topic(3,count_df1)
topic1=pd.DataFrame({'Topic 0':top_words(count_df1, model1, 0, 15),
                   'Topic 1':top_words(count_df1, model1, 1, 15),
                   'Topic 2':top_words(count_df1, model1, 2, 15)
                   })
topic1

              Topic 0            Topic 1         Topic 2
0         house genre        driving mad       track mix
1       facebook page       shadow child        year ago
2           long shot      looking track  mix soundcloud
3          house tech        nick warren         new mix
4         chill house      melodic house    house techno
5         nick warren     mix soundcloud  thanks advance
6             dj koze            new mix      acid house
7            year ago          long shot      house tech
8           twitch tv          house set   classic house
9             hey guy      classic house  house playlist
10      melodic house          hello guy     chill house
11         acid house     track remember      tech house
12  progressive house  progressive house       long shot
13       house techno       original mix       daft punk
14         deep house        house track      house song

In [16]:
#n-gram for fear
count_df2=count_2gram(fear_df['selftext'])
count_df2.head(20)

                words  count
0         house track     15
1          deep house     11
2        original mix     10
3        house techno      8
4          house song      8
5            track id      8
6   progressive house      8
7         anyone help      7
8           long shot      6
9            year ago      5
10         tech house      5
11          bang bang      4
12      era insomniac      4
13     thanks advance      4
14              xb xb      4
15          last week      4
16         mix monday      4
17          twitch tv      4
18          hello guy      4
19          sub genre      4

In [17]:
sadness_df=df[df['label']=='sadness']
#n-grams for sadness
count_df2=count_2gram(sadness_df['selftext'])
count_df2.head(20)

                      words  count
0                 lt iframe     14
1              width height      7
2          encrypted medium      7
3                     gt lt      7
4                 iframe gt      7
5           picture picture      5
6              iframe width      4
7                height src      4
8           src frameborder      4
9         frameborder allow      4
10      allow accelerometer      4
11   accelerometer autoplay      4
12       autoplay encrypted      4
13         medium gyroscope      4
14        gyroscope picture      4
15  picture allowfullscreen      4
16       allowfullscreen gt      4
17                 year ago      4
18                    oh oh      4
19             original mix      4

In [18]:
#topic modeling for sadness
sadness_df=df[df['label']=='sadness']

count_df1=tfidfvectorizer(sadness_df)
model1=nmf_topic(4,count_df1)
topic1=pd.DataFrame({'Topic 0':top_words(count_df1, model1, 0, 15),
                   'Topic 1':top_words(count_df1, model1, 1, 15),
                   'Topic 2':top_words(count_df1, model1, 2, 15),
                     'Topic 3':top_words(count_df1, model1, 3, 15)                   })
topic1

,Topic 0,Topic 1,Topic 2,Topic 3
0,iframe width,dj vanwells dj,released jan,iframe src
1,height src frameborder,lost boy original,jan melbourne australia,iframe src width
2,allow accelerometer autoplay,listen lost boy,jan melbourne,frameborder allowtransparency
3,gyroscope picture picture,listen lost,released jan melbourne,true allow
4,allow accelerometer,original mix dj,australia pay download,allow encrypted
5,frameborder allow,dj vanwells soundcloud,melbourne australia,true allow encrypted
6,encrypted medium gyroscope,boy original mix,melbourne australia pay,lt iframe src
7,frameborder allow accelerometer,mix dj vanwells,pay download zerosyx,src width
8,lt iframe width,mix dj,download zerosyx bandcamp,medium gt lt
9,medium gyroscope picture,vanwells dj,download zerosyx,width height frameborder
10,medium gyroscope,vanwells dj vanwells,zerosyx bandcamp,allowtransparency true allow
11,height src,vanwells soundcloud,zerosyx bandcamp com,allowtransparency true
12,picture picture allowfullscreen,lost boy,bandcamp com,encrypted medium gt
13,iframe width height,boy original,australia pay,medium gt
14,lt iframe,dj vanwells,pay download,lt iframe

In [19]:
joy_df=df[df['label']=='joy']

#n-grams for joy
count_df2=count_2gram(joy_df['selftext'])
count_df2.head(20)

               words  count
0        house track     61
1         deep house     53
2           mvrk shm     47
3        shm reunion     47
4         tech house     46
5              xb xb     38
6          mashup xb     36
7         hope enjoy     35
8         smashup xb     24
9      steve angello     22
10   reunion smashup     22
11       anyone help     21
12           hey guy     21
13           r house     20
14  help appreciated     20
15        house tune     20
16    reunion mashup     20
17     free download     18
18  wondering anyone     18
19         love hear     18

In [20]:
#topic modeling for joy

count_df1=tfidfvectorizer(joy_df)
model1=nmf_topic(5,count_df1)
topic1=pd.DataFrame({'Topic 0':top_words(count_df1, model1, 0, 15),
                   'Topic 1':top_words(count_df1, model1, 1, 15),
                   'Topic 2':top_words(count_df1, model1, 2, 15),
                     'Topic 3':top_words(count_df1, model1, 3, 15),
                     'Topic 4':top_words(count_df1, model1, 4, 15),
                   })
topic1

,Topic 0,Topic 1,Topic 2,Topic 3,Topic 4
0,funky house,hey guy,track sample,new house,year ago
1,house techno,year ago,love feedback,love hear,deep house track
2,year ago,funky house,funky house,love feedback,thanks advance
3,feedback appreciated,house house,house set,year ago,house head
4,house house,little bit,year ago,funky house,hi guy
5,little bit,house set,house tune,thanks advance,house mix
6,thanks advance,new house,love hear,greatly appreciated,love feedback
7,heard song,greatly appreciated,hi guy,house set,house tech
8,love hear,free download,hey guy,house song,house song
9,house tech,hi guy,free download,hi guy,new house
10,house song,love feedback,house house,heard song,feedback appreciated
11,house mix,track sample,house techno,little bit,free download
12,house tune,favorite house,house tech,house tune,xb xb
13,deep house track,deep house track,house mix,hey guy,hey guy
14,deep house,house track,tech house,help appreciated,hope enjoy

In [21]:
disgust_df=df[df['label']=='disgust']

#n-grams for joy
count_df2=count_2gram(disgust_df['selftext'])
count_df2.head(20)

                words  count
0        original mix     22
1         house track     14
2                 z z     14
3   looking something     10
4        looking song     10
5          deep house      9
6       looking track      8
7          tech house      8
8          good house      8
9         anyone good      7
10          show love      7
11       french house      6
12        guy looking      6
13     thanks looking      6
14      track looking      6
15       song similar      6
16      looking house      6
17          ding ding      6
18       looking good      5
19        looking new      5

In [22]:
#topic modeling for disguest

count_df1=tfidfvectorizer(disgust_df)
model1=nmf_topic(5,count_df1)
topic1=pd.DataFrame({'Topic 0':top_words(count_df1, model1, 0, 15),
                   'Topic 1':top_words(count_df1, model1, 1, 15)
                   })
topic1

                Topic 0                Topic 1
0    looking deep house  looking track similar
1          looking deep          sacha robotti
2      house tech house          looking house
3            house tech            guy looking
4            thanks lot        hey guy looking
5         similar track                hey guy
6             hello guy           similar vibe
7            tech house          house looking
8         track looking            house label
9            deep house             house tune
10               hi guy         house playlist
11    progressive house     looking good house
12  looking house track           looking good
13        looking house            looking new
14          house track             good house

In [23]:
surprise_df=df[df['label']=='surprise']

#n-grams for surprise
count_df2=count_2gram(surprise_df['selftext'])
count_df2.head(20)

               words  count
0         house song      7
1         make sense      3
2        couple week      3
3   wondering anyone      3
4            lt song      3
5    absolute banger      3
6           week ago      3
7        couple year      3
8           year ago      3
9          show tell      3
10       beatus homo      2
11      homo brandon      2
12      brandon patr      2
13     track looking      2
14   looking banging      2
15         knee deep      2
16         long shot      2
17     popular track      2
18       point right      2
19   right direction      2

In [24]:
surprise_df

,selftext,score,anger,anticipation,disgust,fear,joy,sadness,surprise,trust,label
22,mix mix named beatus homo brandon patr first t...,1,66,0,56,65,0,0,83,0,surprise
25,several bangin track automatik silk need cajua...,1,0,0,0,65,0,58,83,0,surprise
35,long shot anyone set list raf wood electric pi...,2,119,60,65,73,54,54,128,61,surprise
46,popular track woman humming song occasional check,2,0,0,0,0,0,0,50,0,surprise
54,popular track month sub posted together,1,0,0,0,0,0,0,50,0,surprise
...,...,...,...,...,...,...,...,...,...,...,...
3645,megathread seems obsolete complete stab dark a...,1,84,0,0,67,175,122,248,53,surprise
3646,someone please upload amazing remix barbara tu...,1,0,50,0,71,56,0,84,77,surprise
3738,saw fedde play sensation toronto set song chor...,0,0,0,0,0,0,0,53,0,surprise
3851,looking banging house electro house basically ...,0,0,0,56,65,0,0,83,75,surprise
3877,diz washington posted fb chicago heavy hitter ...,9,66,123,0,187,220,0,251,0,surprise

In [25]:
#topic modeling for surprise
count_df1=tfidfvectorizer(surprise_df)
model1=nmf_topic(5,count_df1)
topic1=pd.DataFrame({'Topic 0':top_words(count_df1, model1, 0, 15)})
topic1

                  Topic 0
0       jackin house week
1              house week
2            heavy jackin
3         guy point right
4        wobbly bass line
5             wobbly bass
6          house week ago
7               bass line
8           wondering guy
9            jackin house
10        direction great
11  right direction great
12  point right direction
13        right direction
14            point right

In [26]:
anger_df=df[df['label']=='anger']

#n-grams for anger
count_df2=count_2gram(anger_df['selftext'])
count_df2.head(20)

                    words  count
0            made content     24
1       soundcloud listen     22
2             house track     21
3              house song     18
4              tech house     17
5            original mix     16
6               lt iframe     16
7            iframe width     16
8            width height     16
9        height scrolling     16
10  scrolling frameborder     16
11           anyone track     15
12      frameborder allow     15
13         allow autoplay     15
14           autoplay src     15
15             deep house     14
16                r house     14
17        listen released     14
18          released swav     14
19        swav soundcloud     14

In [27]:
#topic modeling for anger

count_df1=tfidfvectorizer(anger_df)
model1=nmf_topic(3,count_df1)
topic1=pd.DataFrame({'Topic 0':top_words(count_df1, model1, 0, 15),
                   'Topic 1':top_words(count_df1, model1, 1, 15),
                   'Topic 2':top_words(count_df1, model1, 2, 15)})
topic1

,Topic 0,Topic 1,Topic 2
0,lt iframe width,frameborder allow,monthly stickied
1,height scrolling frameborder,autoplay src,self content
2,lt iframe,allow autoplay src,monthly stickied self
3,house track,lt iframe width,reoccur monthly stickied
4,iframe width,scrolling frameborder,reoccur monthly
5,iframe width height,lt iframe,removed directed
6,height scrolling,iframe width height,content mix
7,listen released swav,iframe width,content mix production
8,released swav soundcloud,height scrolling frameborder,outside post removed
9,released swav,height scrolling,post dedicated
10,listen released,width height,production reoccur monthly
11,swav soundcloud,width height scrolling,production reoccur
12,tech house,deep house,post removed directed
13,deep house,tech house,post dedicated user
14,house song,house track,outside post

anger for:
topic0: insurance company and banks
topic1: loans and time(year ago)
topic2: brokerage account(special for this sentiment)

In [28]:
trust_df=df[df['label']=='trust']

#n-grams for trust
count_df2=count_2gram(trust_df['selftext'])
count_df2.head(20)

                    words  count
0             house track     46
1              deep house     36
2              tech house     36
3                 hey guy     35
4                 dun dun     24
5              house song     24
6                  hi guy     18
7          thanks advance     16
8                 r house     16
9        anyone recommend     15
10             old school     15
11              house mix     14
12               track id     13
13           house techno     13
14        song suggestion     13
15                  xb xb     13
16             house tune     12
17  anyone recommendation     12
18              love hear     12
19           looking song     12

In [29]:
#topic modeling for trust

count_df1=tfidfvectorizer(trust_df)
model1=nmf_topic(5,count_df1)
topic1=pd.DataFrame({'Topic 0':top_words(count_df1, model1, 0, 15),
                   'Topic 1':top_words(count_df1, model1, 1, 15),
                   'Topic 2':top_words(count_df1, model1, 2, 15),
                    'Topic 3':top_words(count_df1, model1, 3, 15),
                    'Topic 4':top_words(count_df1, model1, 4, 15)})
topic1

,Topic 0,Topic 1,Topic 2,Topic 3,Topic 4
0,house mix,year ago,love hear,song suggestion,thanks advance
1,hip hop,new track,thanks help,mall grab,year ago
2,including asking,track heard,good house,help appreciated,hi guy
3,song suggestion,track id,track heard,love house,love hear
4,house head,love house,female vocal,female vocal,mall grab
5,greatly appreciated,heard mix,song similar,love hear,looking house
6,looking song,love hear,need help,year ago,greatly appreciated
7,song similar,female vocal,classic house,house house,good house
8,house house,good house,old school,heard song,thanks help
9,looking house,help appreciated,mall grab,need help,house tune
10,help appreciated,thanks advance,recommend similar,old school,track heard
11,love hear,classic house,help appreciated,house mix,hip hop
12,thanks advance,hi guy,love house,hi guy,house house
13,thanks help,looking house,house tune,house techno,house mix
14,house song,house track,hey guy,tech house,deep house