In [5]:
import pandas as pd
from pmaw import PushshiftAPI
api = PushshiftAPI()
import datetime as dt
before = int(dt.datetime(2021,2,1,0,0).timestamp())
after = int(dt.datetime(2013,12,1,0,0).timestamp())
print(before)
print(after)
subreddit="house"
limit=100000
comments = api.search_comments(subreddit=subreddit, limit=limit, before=before, after=after)
comments_df = pd.DataFrame(comments)
# preview the comments data
comments_df.head(5)

1612108800
1385827200

Not all PushShift shards are active. Query results may be incomplete.

98821 result(s) not found in Pushshift

Not all PushShift shards are active. Query results may be incomplete.
Not all PushShift shards are active. Query results may be incomplete.
Not all PushShift shards are active. Query results may be incomplete.
Not all PushShift shards are active. Query results may be incomplete.

Total:: Success Rate: 100.00% - Requests: 16 - Batches: 4 - Items Remaining: 0

,author,author_created_utc,author_flair_css_class,author_flair_text,author_fullname,body,controversiality,created_utc,distinguished,gilded,...,total_awards_received,author_cakeday,associated_award,author_premium,awarders,collapsed_because_crowd_control,treatment_tags,comment_type,top_awarded_type,steward_reports
0,Sanjay24,1.427462e+09,None,None,t2_mit8x,"Hi...\nThis is Sanjay from NITK surathkal, ind...",0.0,1427462344,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,turkianos,1.423627e+09,None,None,t2_lagrf,I'm new to this so I didn't know. Thanks for t...,0.0,1424438235,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,mrsmunson,1.294787e+09,None,None,t2_4ps80,This is a pretty quiet subreddit. I doubt the...,0.0,1423705557,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,CampbellPlays,1.408929e+09,None,None,t2_i1956,It obviously *didnt happen* almost every thing...,0.0,1422397688,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,[deleted],NaN,None,None,NaN,[deleted],0.0,1421759119,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
comments_df.to_csv('./wsb_comments.csv', header=True, index=False, columns=list(comments_df.axes[1]))

In [8]:
df=pd.read_csv('wsb_comments.csv')
df=df[['author','body','created_utc','score','subreddit']]
df

,author,body,created_utc,score,subreddit
0,Sanjay24,"Hi...\nThis is Sanjay from NITK surathkal, ind...",1427462344,1,housing
1,turkianos,I'm new to this so I didn't know. Thanks for t...,1424438235,1,housing
2,mrsmunson,This is a pretty quiet subreddit. I doubt the...,1423705557,1,housing
3,CampbellPlays,It obviously *didnt happen* almost every thing...,1422397688,1,housing
4,[deleted],[deleted],1421759119,1,housing
...,...,...,...,...,...
1174,bluestreak711,It has to be up to you and I do not know the s...,1576774369,1,housing
1175,bluestreak711,Most rent houses require you get your own abli...,1576774156,1,housing
1176,bluestreak711,"I know, but are there any organizations that ...",1576773548,1,housing
1177,DirtyPondPickles,This is the norm with renting. You almost alwa...,1576772250,1,housing
1178,nyankana,Very nice bathroom indeed!! 😁😁,1576615837,1,housing

In [9]:
import pandas as pd
from pmaw import PushshiftAPI
api = PushshiftAPI()
import datetime as dt
before = int(dt.datetime(2021,2,1,0,0).timestamp())
after = int(dt.datetime(2013,2,1,0,0).timestamp())
print(before)
print(after)
subreddit="house"
limit=100000
submissions = api.search_submissions(subreddit=subreddit, limit=limit, before=before, after=after)
submissions_df = pd.DataFrame(submissions)
# preview the comments data
submissions_df.head(5)

1612108800
1454256000

Not all PushShift shards are active. Query results may be incomplete.

90849 result(s) not found in Pushshift

Not all PushShift shards are active. Query results may be incomplete.
Not all PushShift shards are active. Query results may be incomplete.
Not all PushShift shards are active. Query results may be incomplete.
Not all PushShift shards are active. Query results may be incomplete.
Not all PushShift shards are active. Query results may be incomplete.
Not all PushShift shards are active. Query results may be incomplete.
Not all PushShift shards are active. Query results may be incomplete.
Not all PushShift shards are active. Query results may be incomplete.
Not all PushShift shards are active. Query results may be incomplete.
Not all PushShift shards are active. Query results may be incomplete.
Not all PushShift shards are active. Query results may be incomplete.
Not all PushShift shards are active. Query results may be incomplete.

Total:: Success Rate: 100.00% - Requests: 115 - Batches: 12 - Items Remaining: 8

Not all PushShift shards are active. Query results may be incomplete.

8 result(s) not found in Pushshift

,author,author_created_utc,author_flair_css_class,author_flair_text,author_fullname,created_utc,domain,full_link,gilded,id,...,wls,url_overridden_by_dest,poll_data,gallery_data,is_gallery,media_metadata,og_description,og_title,steward_reports,removed_by
0,paradisenoir,1.461872e+09,None,None,t2_xj9vh,1469810090,self.Adulting,https://www.reddit.com/r/Adulting/comments/4v7...,0.0,4v7gzy,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,emptysometimes,1.452979e+09,None,None,t2_tuub6,1469550546,youtu.be,https://www.reddit.com/r/Adulting/comments/4up...,0.0,4upi1t,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,PortlandPerson94,1.450721e+09,None,None,t2_t4xsl,1468814980,self.Adulting,https://www.reddit.com/r/Adulting/comments/4td...,0.0,4tdb9b,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,thisisthetyty,1.467309e+09,None,None,t2_z57zl,1467816249,youtube.com,https://www.reddit.com/r/Adulting/comments/4ri...,0.0,4rit1y,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,writer318,1.464190e+09,None,None,t2_y7cco,1467729176,theodysseyonline.com,https://www.reddit.com/r/Adulting/comments/4rc...,0.0,4rcy8p,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
submissions_df.to_csv('./wsb_submissions.csv', header=True, index=False, columns=list(submissions_df.axes[1]))

In [11]:
df2=pd.read_csv('wsb_submissions.csv')

df2.columns
columns=['author','created_utc', 'domain',
       'full_link', 'num_comments', 'over_18', 'score','selftext', 'subreddit', 'title','num_crossposts']
df2=df2[columns]
df2

C:\Users\ymf\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (3,34,35,36,40,41,45,48,49,54,55,63,64,65,66,67,70,73,75,92,93,94,95) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,author,created_utc,domain,full_link,num_comments,over_18,score,selftext,subreddit,title,num_crossposts
0,paradisenoir,1469810090,self.Adulting,https://www.reddit.com/r/Adulting/comments/4v7...,1,False,1,I seriously didn't know where to put this ques...,Adulting,Need help with Updating driver's License,NaN
1,emptysometimes,1469550546,youtu.be,https://www.reddit.com/r/Adulting/comments/4up...,0,False,1,NaN,Adulting,Adulting 101,NaN
2,PortlandPerson94,1468814980,self.Adulting,https://www.reddit.com/r/Adulting/comments/4td...,1,False,4,"How to do laundry, organize your filing cabine...",Adulting,"in the spirit of the discription of this sub, ...",NaN
3,thisisthetyty,1467816249,youtube.com,https://www.reddit.com/r/Adulting/comments/4ri...,0,False,1,NaN,Adulting,New youtube video about symptoms of adulting. ...,NaN
4,writer318,1467729176,theodysseyonline.com,https://www.reddit.com/r/Adulting/comments/4rc...,0,False,1,NaN,Adulting,"Why Must We Have To ""Adult""?",NaN
...,...,...,...,...,...,...,...,...,...,...,...
9138,idkwtfidbihtfiosh,1599701236,self.Adulting,https://www.reddit.com/r/Adulting/comments/ipt...,2,False,1,[removed],Adulting,Splitting households and taking over financial...,0.0
9139,Hairy_Otter00,1599700312,self.Adulting,https://www.reddit.com/r/Adulting/comments/ipt...,7,False,1,"By mental load, I am referring to the near-con...",Adulting,What can we do to lift the mental load?,0.0
9140,thedebtreliefco,1599697896,interest.com,https://www.reddit.com/r/Adulting/comments/ips...,0,False,1,NaN,Adulting,Survival Guide for Young Adults Back Home Duri...,0.0
9141,mrcashflow92,1599684818,i.redd.it,https://www.reddit.com/r/Adulting/comments/ipo...,56,False,1,NaN,Adulting,What type of plug in is this? What is it used ...,0.0
9142,cornerstorequeer,1599683148,self.Adulting,https://www.reddit.com/r/Adulting/comments/ipo...,3,False,1,"Hi, I'm 18, so barely an adult, lol. But I don...",Adulting,Help Seeking Mental Help?,0.0

In [12]:
df2.to_csv('CaliHouse.csv')